### ISSUE TITLE
Syntax error for ruby < 3.1 with value omitted from keyword argument 'hook'

### ISSUE THREAD

**Issue by biinari** [gael-ian/vagrant-bindfs#110]
In 1.3.0, the value for the `hook:` argument is omitted. Doing so is a feature introduced in [Ruby 3.1](https://rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted)

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': /home/bill/.vagrant.d/gems/3.0.2/gems/vagrant-bindfs-1.3.0/lib/vagrant-bindfs/vagrant/actions/mounter.rb:30: syntax error, unexpected ')' (SyntaxError)
....actions.mounter.start', hook:)
...                              ^
/home/bill/.vagrant.d/gems/3.0.2/gems/vagrant-bindfs-1.3.0/lib/vagrant-bindfs/vagrant/actions/mounter.rb:31: syntax error, unexpected `do' for block, expecting `end'
...und_folders(hook).each_value do |folder|
...                             ^~
/home/bill/.vagrant.d/gems/3.0.2/gems/vagrant-bindfs-1.3.0/lib/vagrant-bindfs/vagrant/actions/mounter.rb:107: syntax error, unexpected `end', expecting end-of-input
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/bill/.vagrant.d/gems/3.0.2/gems/vagrant-bindfs-1.3.0/lib/vagrant-bindfs/vagrant/plugin.rb:20:in `block (3 levels) in <class:Plugin>'
	from /home/bill/.vagrant.d/gems/3.0.2/gems/vagrant-bindfs-1.3.0/lib/vagrant-bindfs/vagrant/plugin.rb:19:in `each'
	from /home/bill/.vagrant.d/gems/3.0.2/gems/vagrant-bindfs-1.3.0/lib/vagrant-bindfs/vagrant/plugin.rb:19:in `block (2 levels) in <class:Plugin>'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:283:in `block in apply_action_name'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:282:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:282:in `apply_action_name'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:185:in `to_app'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

Ruby version: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
vagrant version: `Vagrant 2.2.19`
OS: Ubuntu 22.04.4 LTS

**Comment by gael-ian** [comment]
Hi @biinari 

Sorry about that. It's now fixed in the new 1.3.1 release.
