### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by 262media** [gael-ian/vagrant-bindfs#48]
Trying to install on osx and getting this error

> Installing the 'vagrant-bindfs' plugin. This can take a few minutes...
> Bundler, the underlying system Vagrant uses to install plugins,
> reported an error. The error is shown below. These errors are usually
> caused by misconfigured plugin installations or transient network
> issues. The error from Bundler is:
> 
> An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
> Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.
> 
> Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
>     /opt/vagrant/embedded/bin/ruby -r ./siteconf20160721-10219-1pot6r1.rb extconf.rb
> checking for ffi.h... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
> 	--with-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
> 	--with-ffi_c-dir
> 	--without-ffi_c-dir
> 	--with-ffi_c-include
> 	--without-ffi_c-include=${ffi_c-dir}/include
> 	--with-ffi_c-lib
> 	--without-ffi_c-lib=${ffi_c-dir}/lib
> 	--with-libffi-config
> 	--without-libffi-config
> 	--with-pkg-config
> 	--without-pkg-config
> /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:524:in `with_werror'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:321:in `open'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:321:in `open'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
> 	from /opt/vagrant/embedded/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
> 	from extconf.rb:16:in `<main>'
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /Users/rui/.vagrant.d/gems/gems/ffi-1.9.14 for inspection.
> Results logged to /Users/rui/.vagrant.d/gems/extensions/universal-darwin-12/2.2.0/ffi-1.9.14/gem_make.out

**Comment by 262media** [comment]
This was caused by an outdated vagrant version
