### ISSUE TITLE
The bind command `bindfs --force-user=vagrant --force-group=vagrant ...` failed to run!

### ISSUE THREAD

**Issue by klierik** [gael-ian/vagrant-bindfs#53]
Hello there.
I have some wired error and Google not help with solution :(

```
$ vagrant plugin list
vagrant-bindfs (0.4.11)
vagrant-hostmanager (1.8.5)
vagrant-share (1.1.5, system)
vagrant-vmware-fusion (4.0.14)

$ vagrant -v
Vagrant 1.8.7
```

So when i run `$ vagrant up/reload --debug` it says:
```
...
/opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:308:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:189:in `<main>'
 INFO interface: error: The bind command `bindfs --force-user=vagrant --force-group=vagrant --perms=u=rwX:g=rD:o=rD /vagrant-nfs /vagrant/httpdocs` failed to run!

Please check options values and compatibility. For a complete documentation,
run `sudo bindfs --help` on the VM.

You can see it online at http://bindfs.org/docs/bindfs.1.html
The bind command `bindfs --force-user=vagrant --force-group=vagrant --perms=u=rwX:g=rD:o=rD /vagrant-nfs /vagrant/httpdocs` failed to run!

Please check options values and compatibility. For a complete documentation,
run `sudo bindfs --help` on the VM.

You can see it online at http://bindfs.org/docs/bindfs.1.html
```

Can you tell me please how to fix it?

Thanks

**Comment by gael-ian** [comment]
Hi,

Can you tell me what are your host and guest OSes and add a copy of your Vagrantfile please ?

Thank you

**Comment by klierik** [comment]
host: macOS latest
guest: Ubuntu 14.04

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    ## VirtualBox
    # config.vm.box = "ubuntu/trusty64"
    ## VMWare
    config.vm.box = "jpease/ubuntu-trusty"

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    ## VirtualBox
    # config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20161103.0.0/providers/virtualbox.box"
    ## VMWare
    # config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    # Provision
    config.vm.provision :shell, :path => "provision/provision.sh"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    config.vm.network :forwarded_port, guest: 80, host: 8912
    config.vm.network :forwarded_port, guest: 22, host: 2213


    # Synced folder via NFS
    ## VMWare NFS Enable (vagrant-bindfs required)
    config.vm.synced_folder     "../magento/", "/vagrant-nfs", type: "nfs"
    config.bindfs.bind_folder   "/vagrant-nfs", "/vagrant/httpdocs"

    # Synced folder via defaults
    ## Default
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs", id: "vagrant-root", owner: "vagrant", group: "www-data", mount_options: ["dmode=775,fmode=664"]

    ## VirtualBox + NFS
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs", nfs: true, mount_options: ["nolock", "async"], bsd__nfs_options: ["alldirs","async","nolock"]


    # VirtualBox settings
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end

    # VMWare settings
    config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = "1024"
        v.vmx["numvcpus"] = "1"
    end


    # Host Manager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define 'glasstileoasis' do |node|
        node.vm.hostname = 'glasstileoasis'
        node.vm.network :private_network, ip: '192.168.10.11'
        node.hostmanager.aliases = %w(glasstileoasis.dev www.glasstileoasis.dev www.gto.dev gto.dev)
    end
end
```

**Comment by gael-ian** [comment]
Thanks you for these information's.

I've never tested the plugin with VMware but I think there is no reason it won't work the same as with Virtual box.

Can you try to mount the bonded folder in another position ? I think Vagrant may use the '/vagrant' directory for its own usage. Except that, I can't see nothing wrong in your configuration and I will need more time to do some tests but will only be able to do them in a few days.

Hope this helps

**Comment by klierik** [comment]
you mean update row `config.bindfs.bind_folder   "/vagrant-nfs", "/vagrant/httpdocs"` to something like `config.bindfs.bind_folder   "/vagrant-nfs", "/httpdocs"` ?

btw, i can try re-create with VBox instead of VMWare...

**Comment by gael-ian** [comment]
Exactly.

You can keep on VMware for now and switch back to Virtualbox only if it doesn't work.

Thanks you

**Comment by klierik** [comment]
actually you was wright...
```
    ## Sync with vagrant-bindfs
    config.vm.synced_folder     "../magento/", "/vagrant-nfs", type: "nfs"
    config.bindfs.bind_folder   "/vagrant-nfs", "/srv/http/"
```

in this way `/srv/http/` working perfect. it's seems something was changed in Vangrant environment.
a couple moth ago path `/vagrant/httpdocs/` worked perfect

**Comment by gael-ian** [comment]
Glab we could have it fixed so quickly :)
Thanks for reporting, I will amend the documentation to add a note about that.
