### ISSUE TITLE
OS X : Undefined  constant Vagrant::Action::Builtin::NFS

### ISSUE THREAD

**Issue by loic-roux-404** [gael-ian/vagrant-bindfs#91]
- Mac os Catalina && Vagrant 2.2.6 / 2.2.7dev
- bindfs 1.1.5
- Tried to rebuild vagrant from master branch not working

Have you a simple workaround ?

The error : 
```
/Users/loic/.vagrant.d/gems/2.4.9/gems/vagrant-bindfs-1.1.5/lib/vagrant-bindfs/vagrant/plugin.rb:38:in `synced_folders_hook': uninitialized constant Vagrant::Action::Builtin::NFS (NameError)
	from /Users/loic/.vagrant.d/gems/2.4.9/gems/vagrant-bindfs-1.1.5/lib/vagrant-bindfs/vagrant/plugin.rb:30:in `hooks'
	from /Users/loic/.vagrant.d/gems/2.4.9/gems/vagrant-bindfs-1.1.5/lib/vagrant-bindfs/vagrant/plugin.rb:19:in `block (2 levels) in <class:Plugin>'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:56:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:55:in `tap'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:55:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:54:in `map'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:54:in `run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:613:in `lock'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/reload/command.rb:42:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/reload/command.rb:40:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
```

**Comment by gael-ian** [comment]
Hi @loic-roux-404 

`Vagrant::Action::Builtin::NFS` disappeared more than four years ago and should not be detected as existing. In fact, it does not exist at this time in Vagrant's codebase, given a quick look.

I have to dig deeper to understand what changed in Vagrant but I can't do it before a few days. For now, you can install an older release of Vagrant (2.2.5 should be fine).

Sorry for the inconvenience

**Comment by loic-roux-404** [comment]
Thanks !

**Comment by gael-ian** [comment]
There's currently [a bug](https://github.com/hashicorp/vagrant/issues/11293) that prevents to run Vagrant in development mode. I can't do anything  as long as this bug is not fixed, as it also exists in Vagrant 2.2.5 and Vagrant 2.2.4 does not recognize Virtualbox as installed on my system.

What is your system's Ruby version? (Try running `ruby -v && gem list` in a Terminal)
What was your first method to install Vagrant ?
Why did you install bindfs on your system ? (it's only needed on the _guest_ system and vagrant-bindfs ensure it's installed before trying to bind any folders)

**Comment by loic-roux-404** [comment]
yes i have `bindfs` on my machine and it's not far to working correctly but if you have a solution with your plugin i prefer.
my ruby version ruby `2.6.3p62`

i have installed vagrant by following [this](https://www.vagrantup.com/docs/installation/source.html)

gems
```
addressable (2.7.0)
bcrypt_pbkdf (1.0.1)
bigdecimal (default: 1.4.1)
builder (3.2.4, 3.2.3)
bundler (default: 1.17.2)
CFPropertyList (2.3.6)
childprocess (0.6.3)
cmath (default: 1.0.0)
concurrent-ruby (1.1.5)
crack (0.4.3)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
diff-lcs (1.3)
domain_name (0.5.20190701)
e2mmap (default: 0.1.0)
ed25519 (1.2.4)
erubi (1.9.0)
erubis (2.7.0)
etc (default: 1.0.1)
fake_ftp (0.1.1)
fcntl (default: 1.0.0)
ffi (1.11.3)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gssapi (1.3.0)
gyoku (1.3.1)
hashdiff (1.0.0)
hashicorp-checkpoint (0.1.5)
http-cookie (1.0.3)
httpclient (2.8.3)
i18n (1.8.2, 1.8.1, 1.7.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
libxml-ruby (3.1.0)
listen (3.1.5)
little-plugger (1.1.4)
log4r (1.1.10)
logger (default: 1.3.0)
logging (2.2.2)
matrix (default: 0.1.0)
mime-types (3.3.1, 3.3)
mime-types-data (3.2019.1009)
mini_portile2 (2.4.0)
minitest (5.11.3)
multi_json (1.14.1)
mutex_m (default: 0.1.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (5.1.0)
net-telnet (0.2.0)
netrc (0.11.0)
nokogiri (1.10.1)
nori (2.6.0)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.3, 4.0.1)
rake (12.3.2, 12.0.0)
rb-fsevent (0.10.3)
rb-inotify (0.10.1, 0.10.0)
rb-kqueue (0.2.5)
rdoc (default: 6.1.0)
rest-client (2.0.2)
rexml (default: 3.1.9)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-its (1.3.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
rss (default: 0.2.7)
ruby_dep (1.3.1)
rubyntlm (0.6.2)
rubyzip (1.3.0)
safe_yaml (1.0.5)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
sqlite3 (1.3.13)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thor (0.18.1)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
unf (0.1.4)
unf_ext (0.0.7.6)
vagrant_cloud (2.0.3)
wdm (0.1.1)
webmock (2.3.2)
webrick (default: 1.4.2)
winrm (2.3.4, 2.3.3)
winrm-elevated (1.1.2)
winrm-fs (1.3.3)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

**Comment by gael-ian** [comment]
Hi @loic-roux-404 

The plugin is supposed to handle both installation of bindfs in your VM (you don't need to install it on your host machine) and folders binding on startup. Your workaround seems find to me but ight prove to be more complicated to maintain on the long run.

Is there a reason why you had to install Vagrant from sources instead of the recommended official installer ?
This may be the source of the problem…

**Comment by loic-roux-404** [comment]
I juste use direct bindfs command Line to fix my case. I try vagrant from source just for get last features and i Also try other versions but under 2.2.0 it's require Virtual box 5 and i don't want to downgrade it.

My workaround is enough for me i Also try to set the Vagrant::Action::Builtin::NFS to true but's i didn't quote any change on the folder perms.

**Comment by gael-ian** [comment]
The problem comes from `Vagrant::Action::Builtin::NFS` detected as existing at first ([here](https://github.com/gael-ian/vagrant-bindfs/blob/master/lib/vagrant-bindfs/vagrant/plugin.rb#L37)) then proved to be undefined (on next ligne), as it should be since Vagrant 1.something and still is, as this constant does not appear anywhere is Vagrant's sources.

Do you have any other plugin installed?
Can you please post your Vagrantfile here?

As long as Vagrant's issue #11293 isn't solved, I'm afraid I can't do much :/

**Comment by loic-roux-404** [comment]
Yes thank you, that doesn't matter. I have vagrant hostmanager plugin installed.
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir      = File.dirname(File.expand_path(__FILE__))
yml              = YAML.load_file("#{current_dir}/config.yaml")
conf, vm         =  yml['conf'], yml['vm']
# If you're on a new build of Windows 10 you can try to use NFS
os               = "bento/debian-" + conf['os']
# book repo
playbook_name    = "playbook-#{conf['projectname']}"
playbook         = "https://github.com/#{conf['org']}/#{playbook_name}.git" 

### work path variable to change in debug mode
# Be aware of shared folders when deleting things
debug            = conf['debug_playbook']
folder           = debug ? '/vagrant' : '/tmp'
web_dir          = "/data/#{conf['projectname']}/#{conf['web_path']}"
# nfs config
conf['nfs'] = Vagrant::Util::Platform.darwin? || Vagrant::Util::Platform.linux?
NFS = conf['nfs'] && ARGV[1] != '--provision' && (File.exist? File.dirname(__FILE__) + "/.vagrant/machines/default/virtualbox/action_provision")
# ssl config
hosts            = ""

if !Vagrant.has_plugin?('vagrant-hostmanager')
  puts "The vagrant-hostmanager plugin is required. Please install it with \"vagrant plugin install vagrant-hostmanager\""
  exit
end
hosts << conf['servername'] << " "
hosts << "api." << conf['servername'] << " "

Vagrant.require_version ">= 2.2.2"

Vagrant.configure(2) do |config|
  config.vm.box = os
  
  id_rsa_path        = File.join(Dir.home, ".ssh", "id_rsa")
  id_rsa_ssh_key     = File.read(id_rsa_path)
  id_rsa_ssh_key_pub = File.read(File.join(Dir.home, ".ssh", "id_rsa.pub"))
  insecure_key_path  = File.join(Dir.home, ".vagrant.d", "insecure_private_key")

  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  config.ssh.private_key_path = [id_rsa_path, insecure_key_path]

  config.vm.provider "virtualbox" do |vb|
      vm.each do |name, param|
        vb.customize ["modifyvm", :id, "--#{name}", param]
      end
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  #config.vm.network "forwarded_port", guest: 3306, host: 3366

  config.vm.hostname = conf['servername']
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.hostmanager.aliases = hosts
  config.vm.network :private_network, ip: conf['private_ip']

  if !debug
    config.vm.synced_folder ".", "/vagrant", disabled: true

    $init = <<-SCRIPT
    sudo apt -y install git
    rm -rf /tmp/#{playbook_name} || true
    git clone #{playbook} /tmp/#{playbook_name}
    SCRIPT
    
    config.vm.provision "shell", inline: $init, privileged: false  
  end

  ## Install and configure software
  config.vm.provision "ansible_local" do |ansible|
      ansible.provisioning_path = "#{folder}/#{playbook_name}/"
      ansible.playbook = "playbook.yml"
      ansible.become = true
      ansible.verbose = ""
      ansible.extra_vars = conf
  end

  if NFS
    # NFS config / bind vagrant user to nfs mount
    if Vagrant::Util::Platform.darwin?
        config.vm.synced_folder "./www", "#{web_dir}", type: "nfs", nfs_version: 3, nfs_udp: true,
        mount_options: ['rw','fsc','noac','actimeo=1','async'],
        linux__nfs_options: ['rw','all_squash','insecure','no_subtree_check','async']
        # fix bad user binding when mounting from OS X catalina / mojave
        config.vm.provision :shell, :inline => "sudo bindfs --map=501/vagrant:@dialout/@vagrant --perms=u=rwx,g=rx,o=rx #{web_dir} #{web_dir}", run: 'always'
    else
      # linux nfs 4 server
      config.vm.synced_folder "./www", "#{web_dir}", type: "nfs", nfs_version: 4, nfs_udp: false, mount_options: ['rw','noac','actimeo=2']
    end
  else
    # reload nfs / shared folder after provision
    config.trigger.after :provision do |t|
      t.info = "Reboot after provisioning"
      t.run = { :inline => "vagrant reload" }
    end
  end

  # fix ssh common issues
  ssh_path = "/home/vagrant/.ssh"
  config.vm.provision :shell, :inline => "echo '#{id_rsa_ssh_key }' > #{ssh_path}/id_rsa && chmod 600 #{ssh_path}/id_rsa"
  config.vm.provision :shell, :inline => "echo '#{id_rsa_ssh_key_pub }' > #{ssh_path}/authorized_keys && chmod 600 #{ssh_path}/authorized_keys"
end
```

**Comment by gael-ian** [comment]
Ok, I think I just found the problem. Can you try to rename the variable `NFS` defined on line 21 in your Vagrantfile to something else (it's also used further, line 86 I think), replace your workaround with a call to vagrant-bindfs' `bind_folder` and run `vagrant up`?

The call to `const_defined?` linked in my previous comment is supposed to look for a `NFS` constant inside the `Vagrant::Action::Builtin` module but, according to Ruby's name resolution rules, it certainly look into upper modules for it as long as nothing is found, straight to your Vagrantfile's `NFS`.

If variable renaming solves the problem, I'll try to find a stricter way to detect if `Vagrant::Action::Builtin:NFS` exists as soon as I can (or just drop that piece of code as it's here only for backward compatibility with long gone versions of Vagrant…)

**Comment by loic-roux-404** [comment]
> Ok, I think I just found the problem. Can you try to rename the variable `NFS` defined on line 21 in your Vagrantfile to something else (it's also used further, line 86 I think), replace your workaround with a call to vagrant-bindfs' `bind_folder` and run `vagrant up`?
> 
> The call to `const_defined?` linked in my previous comment is supposed to look for a `NFS` constant inside the `Vagrant::Action::Builtin` module but, according to Ruby's name resolution rules, it certainly looks into upper modules for it as long as nothing is found, straight to your Vagrantfile's `NFS`.
> 
> If variable renaming solves the problem, I'll try to find a stricter way to detect if `Vagrant::Action::Builtin:NFS` exists as soon as I can (or just drop that piece of code as it's here only for backward compatibility with long gone versions of Vagrant…)

Sorry i forgot to respond. Work perfectly now by renaming the `NFS` var to `NFS_ENABLED`

Thanks !!

**Comment by gael-ian** [comment]
Thanks @loic-roux-404 for your feedback.

I reopen this issue as a reminder to either find a more strict detection strategy or drop that piece of backward compatibility before the next release.
